apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciao-deployment
  labels:
    app: ciao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciao
  template:
    metadata:
      labels:
        app: ciao
    spec:
      containers:
      - name: ciao
        image: gaocegege/ciao:v0.0.1
        ports:
        - containerPort: 8889

---

apiVersion: v1
kind: Service
metadata:
  name: ciao
  labels:
    app: ciao
spec:
  ports:
  - port: 8889
    protocol: TCP
  selector:
    app: ciao
